language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t brixa/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true brixa/react-test npm test

after_success:
 - docker build -t brixa/multi-client ./client
 - docker build -t brixa/multi-nginx ./nginx
 - docker build -t brixa/multi-server ./server
 - docker build -t brixa/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push brixa/multi-client
 - docker push brixa/multi-nginx
 - docker push brixa/multi-server
 - docker push brixa/multi-worker

deploy:
 provider: elasticbeanstalk
 region: eu-central-1
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-eu-central-1-740989051472
 bucket_path: docker-multi
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: 
  secure: $AWS_SECRET_KEY 
